* Introduction
The ARGA transformer takes input files with a supported format and uses an RDF Turtle schema to transform that input into triples allowing us to represent datasets as a data model for use within the ARGA ecosystem.

The purpose of this is to allow a consistent point of access to data for further processing without changing the source data to ensure reproducibility and provenance. In addition to preserving the original data source it allows us to version the schema used for a specific instance of processing.


* Goals
- Transform from one data model to a common ARGA data model.
- Transform data the same way it was transformed the first time.
- Provide an implementation for operations used in schemas.


* How it works
The transformer is purely a library that will take any stream of triples and load it up into the internal RDF store. Once in the internal store the library user can retrieve transformed records as defined by the selected schema.

The library user is responsible for supplying the input as triples in the form of:
- a record index
- a field name
- and the field value

The transformer loads each triple into the specified graph making the underlying store a TriG store. It is important that this process is as minimal as possible to best represent the original source in a triples representation.
The internal store can then be iterated upon and the transformer will process each field in the record according to the operators defined in the selected schema, thus allowing us to also transform the data into an appropriate value, type, and format rather than just mapping it from one column to another.


* Why?
One of ARGA's key commitment is the ability to reconstruct the data it presents at any point in time. This means that we have to ensure the older datasets are not presented differently due to bug fixes or different mapping, as ARGA's operations logger is responsible for tracking and representing those changes over time.
By using the RDF Turtle format we can declaratively transform data while still supporting a kind of Domain Specific Language (DSL) by allowing a list of operators to apply on a field. While this preserves the original dataset and the transformation /intention/ by including the schema file, it does not preserve the implementation of the transformation which can still lead to errors and must also be preserved. Effectively any inclusion of the schema file must also include the version of this transformer crate so that old or broken implementations can be executed to appropriately transform the data for the purposes of preservation.
